# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-19 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='additional_image',
            field=models.ImageField(null=True, upload_to='addtional_images/'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='hero_image',
            field=models.ImageField(null=True, upload_to='hero_images/'),
        ),
    ]
