# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-19 12:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0003_auto_20151219_1757'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Articles',
            new_name='Article',
        ),
    ]
